# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip --user
        pip install build --user
        pip install pygame --user
        pip install PyOpenGL --user
        pip install tk --user
        pip install pillow --user
        pip install tqdm --user 
        pip install alive-progress --user
        pip install pathlib --user
        pip install setuptools --user
        pip install zipp --user
        pip install urllib3 --user
        pip install requests --user
        pip install colorama --user
        pip install grapheme --user
        pip install certifi --user
        pip install idna --user
        pip install charset-normalizer --user
        pip install logging --user
        pip install noise --user
        pip install numba --user
        pip install moderngl --user
        pip install numpy --user
        pip install PyGLM --user
        pip install opensimplex --user
        pip install ursina --user
    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: Ztrolix
        password: 1wq&ykY7^!qx
